import { register } from "swiper/element/bundle";
import Header from "@/components/header";
import Footer from "@/components/footer";
import type { Metadata } from "next";
import localFont from "next/font/local";

import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "swiper/css/effect-coverflow";
import "@/styles/globals.scss";

const nowRegular = localFont({
  src: "../../public/assets/fonts/now-regular.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

register();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nowRegular.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
